const JOB_TYPE_FULLTIME = "1"
const JOB_TYPE_PARTTIME = "2"
const JOB_TYPE_INTERNSHIP = "3"
const JOB_TYPE_COOP = "4"

export {
  JOB_TYPE_FULLTIME,
  JOB_TYPE_PARTTIME,
  JOB_TYPE_INTERNSHIP,
  JOB_TYPE_COOP
}