const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS"
const ADD_JOB_FAILED = "ADD_JOB_FAILED"
const SAVE_JOB_SUCCESS = "SAVE_JOB_SUCCESS"
const SAVE_JOB_FAILED = "SAVE_JOB_FAILED"
const READ_JOB_SUCCESS = "READ_JOB_SUCCESS"
const READ_JOB_FAILED = "READ_JOB_FAILED"
const AUTH_FAILED = "AUTH_JOB_FAILED"

export {
  ADD_JOB_SUCCESS,
  ADD_JOB_FAILED,
  SAVE_JOB_SUCCESS,
  SAVE_JOB_FAILED,
  READ_JOB_SUCCESS,
  READ_JOB_FAILED,
  AUTH_FAILED
}
