const HOME_PATH = "/"
const LOGIN_PATH = "/login"
const RESULT_PATH = "/result"
const DETAIL_PATH = "/view"
const REGISTER_PATH = "/register"
const APPLY_JOB_PATH = "/apply-job"
const REGISTER_APPLICANT = REGISTER_PATH + "/applicant"
const REGISTER_EMPLOYER = REGISTER_PATH + "/employer"
const TEST_PATH = "/test"

const EMPLOYER_PATH = "/employer"
const EMPLOYER_PROFILE_PATH = EMPLOYER_PATH + "/profile"
const EMPLOYER_JOB_PATH = EMPLOYER_PATH + "/job"
const EMPLOYER_JOB_ADD_PATH = EMPLOYER_JOB_PATH + "/add"
const EMPLOYER_JOB_EDIT_PATH = EMPLOYER_JOB_PATH + "/edit"
const EMPLOYER_RESUME_PATH = EMPLOYER_PATH + "/resume"
const EMPLOYER_SETTING_PATH = EMPLOYER_PATH + "/setting"

const APPLICANT_PATH = "/applicant"
const APPLICANT_PROFILE_PATH = APPLICANT_PATH + "/profile"
const APPLICANT_RESUME_PATH = APPLICANT_PATH + "/resume"
const APPLICANT_APPLYING_PATH = APPLICANT_PATH + "/applying"
const APPLICANT_SETTING_PATH = APPLICANT_PATH + "/setting"

export {
  HOME_PATH,
  LOGIN_PATH,
  RESULT_PATH,
  DETAIL_PATH,
  REGISTER_PATH,
  REGISTER_APPLICANT,
  REGISTER_EMPLOYER,
  APPLY_JOB_PATH,
  TEST_PATH,
  EMPLOYER_PATH,
  APPLICANT_PATH,
  EMPLOYER_PROFILE_PATH,
  EMPLOYER_JOB_PATH,
  EMPLOYER_JOB_ADD_PATH,
  EMPLOYER_JOB_EDIT_PATH,
  EMPLOYER_RESUME_PATH,
  EMPLOYER_SETTING_PATH,
  APPLICANT_PROFILE_PATH,
  APPLICANT_RESUME_PATH,
  APPLICANT_APPLYING_PATH,
  APPLICANT_SETTING_PATH
}