const ADD_SUCCESS = "ADD_SUCCESS"
const ADD_FAILED = "ADD_FAILED"
const SAVE_SUCCESS = "SAVE_SUCCESS"
const SAVE_FAILED = "SAVE_FAILED"
const READ_SUCCESS = "READ_SUCCESS"
const READ_FAILED = "READ_FAILED"
const AUTH_FAILED = "AUTH_FAILED"

export {
  ADD_SUCCESS,
  ADD_FAILED,
  SAVE_SUCCESS,
  SAVE_FAILED,
  READ_SUCCESS,
  READ_FAILED,
  AUTH_FAILED
}
